version: 2.1

commands:

  bootstrap-macos:
    parameters:
      python-version:
        type: string
    steps:
      - run:
          name: Setup MacOS environment
          command: |
            curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh --silent
            bash Miniconda3-latest-MacOSX-x86_64.sh -b -f >> build.log
            ~/miniconda3/bin/conda create -y -n py<< parameters.python-version >> python=<< parameters.python-version >>
            ln -s ~/miniconda3/envs/py<< parameters.python-version >>/bin/python ~/python3
            ~/python3 -m venv py_venv

  bootstrap-win:
    parameters:
      python-version:
        type: string
    steps:
      - run:
          name: Setup Win environment
          command: |
            conda init powershell
            conda create -y -n py-<< parameters.python-version >> python=<< parameters.python-version >>
            conda activate py-<< parameters.python-version >>

  install-python-deps:
    steps:
      - run:
          name: Install Python dependencies
          command: |
            if [ `uname -s` == "Darwin" ]; then
              . py_venv/bin/activate
            fi
            python3 --version
            python3 -m pip install -r requirements.txt
            python3 -m pip install -r requirements-dev.txt
            python3 -m pip install cmake flake8 bandit setuptools-scm
            # python3 -m pip install coverage codacy-coverage

  python-build-test:
    steps:
      - run:
          name: Build & test python
          command: |
            if [ `uname -s` == "Darwin" ]; then
              . py_venv/bin/activate
            fi
            python3 setup.py test --verbose

  flake8-req-check:
    steps:
      - run:
          name: Check code errors (pyflakes)
          command: |
            flake8 --select=F4 --per-file-ignores="__init__.py:F401" .
            flake8 --select=F --per-file-ignores="__init__.py:F401" xun/functions

  flake8-opt-check:
    steps:
      - run:
          name: Check formatting rules (PEP8)
          command: |
            git diff HEAD^ | flake8 --diff --per-file-ignores="__init__.py:F401" --exclude="setup.py"

  bandit-check:
    steps:
      - run:
          name: Bandit security check
          command: |
            bandit -c bandit.yml -r xun

  codacy-check:
    steps:
      - run:
          name: Codacy code coverage check
          command: |
            if [ ! -z "${CODACY_PROJECT_TOKEN}" ]; then
              coverage run setup.py test;
              coverage xml;
              python-codacy-coverage -r coverage.xml;
            fi

  create-sdist:
    steps:
      - run:
          name: Create source package
          command: |
            python3 setup.py sdist

  create-wheel:
    steps:
      - run:
          name: Create wheel
          command: |
            python3 -m pip install cibuildwheel==1.6.0
            python3 -m cibuildwheel --output-dir dist

  upload-pypi:
    steps:
      - run:
          name: Upload to pypi
          command: |
            python3 -m pip install twine
            python3 -m twine upload -u __token__ --skip-existing dist/*

jobs:
  python-code-check:
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - install-python-deps
      - flake8-req-check
      - bandit-check
      - codacy-check

  python-version-check:
    parameters:
      version:
        type: string
    docker:
      - image: "circleci/python:<< parameters.version >>"
    steps:
      - checkout
      - install-python-deps
      - python-build-test

  python-formatting-check:
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - install-python-deps
      - flake8-opt-check

  python-macos-check:
    parameters:
      python-version:
        type: string
    macos:
      xcode: 11.0.0
    steps:
      - checkout
      - bootstrap-macos:
          python-version: << parameters.python-version >>
      - install-python-deps
      - python-build-test

  sdist-deploy:
    docker:
      - image: "circleci/python:3.6"
    steps:
      - checkout
      - install-python-deps
      - create-sdist
      - upload-pypi

  wheels-manylinux-deploy:
    docker:
      - image: "circleci/python:3.6"
    environment:
      - CIBW_BUILD: "cp35-manylinux_x86_64 cp36-manylinux_x86_64 cp37-manylinux_x86_64 cp38-manylinux_x86_64"
      - CIBW_BEFORE_ALL: "yum install -y gcc ninja-build"
      - CIBW_BEFORE_BUILD: "pip install cmake setuptools-scm -r requirements.txt && pip install -r requirements-dev.txt"
    steps:
      - checkout
      - setup_remote_docker
      - create-wheel
      - upload-pypi

  wheels-macos-deploy:
    macos:
      xcode: 11.0.0
    environment:
      - CIBW_BUILD: "cp35-macosx_x86_64 cp36-macosx_x86_64 cp37-macosx_x86_64 cp38-macosx_x86_64"
      - CIBW_BEFORE_BUILD: "pip3 install cmake setuptools-scm -r requirements.txt && pip3 install -r requirements-dev.txt"
    steps:
      - checkout
      - create-wheel
      - upload-pypi
  
  appimage-upload:
    docker:
      - image: "circleci/python:3.8"
    environment:
      - VERSION: 0.1
    steps:
      - run:
          name: Create python3.8 based AppImage
          command: |
            python -m pip install python_appimage
            python -m python_appimage build local -d ./python3.8.AppImage -p /usr/local/bin/python
      - run:
          name: Install Xun to image
          command: |
            ./python3.8.AppImage --appimage-extract
            ./squashfs-root/AppRun -m pip install git+https://github.com/equinor/xun.git
      - run: 
          name: Setup Xun AppImage
          command: |
            sed -i -e 's|/opt/python3.8/bin/python3.8|/usr/bin/xun|g' ./squashfs-root/AppRun
            mv squashfs-root/usr/share/applications/python3.8.6.desktop squashfs-root/usr/share/applications/xun.desktop
            sed -i -e 's|^Name=.*|Name=Xun|g' squashfs-root/usr/share/applications/*.desktop
            sed -i -e 's|^Exec=.*|Exec=Xun|g' squashfs-root/usr/share/applications/*.desktop
            sed -i -e 's|^Icon=.*|Icon=xun|g' squashfs-root/usr/share/applications/*.desktop
            rm squashfs-root/*.desktop
            cp squashfs-root/usr/share/applications/*.desktop squashfs-root/
            mv squashfs-root/python.png squashfs-root/xun.png
            mv squashfs-root squashfs-root-xun
      - run:
          name: Convert back into an AppImage
          command: |
            wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
            chmod +x appimagetool-*.AppImage
            ./appimagetool-587-x86_64.AppImage --appimage-extract
            ./squashfs-root/AppRun squashfs-root-xun/
      - run:
          name: Upload AppImage
          command: |
            echo "upload appimage now"


workflows:
  version: 2

  linux-check:
    jobs:
      - python-version-check:
          name: Python 3.5
          version: "3.5"
      - python-version-check:
          name: Python 3.6
          version: "3.6"
      - python-version-check:
          name: Python 3.7
          version: "3.7"
      - python-version-check:
          name: Python 3.8
          version: "3.8"

  macos-check:
    jobs:
      - python-macos-check:
          name: MacOS Python 3.5
          python-version: "3.5"
      - python-macos-check:
          name: MacOS Python 3.6
          python-version: "3.6"
      - python-macos-check:
          name: MacOS Python 3.7
          python-version: "3.7"
      - python-macos-check:
          name: MacOS Python 3.8
          python-version: "3.8"

  linux-deploy:
    jobs:
      - sdist-deploy:
          name: Create and deploy sdist
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - wheels-manylinux-deploy:
          name: Create and deploy linux wheels
          requires:
            - Create and deploy sdist
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

  macos-deploy:
    jobs:
      - wheels-macos-deploy:
          name: Create and deploy macos wheels
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

  code-check:
    jobs:
      - python-code-check:
          name: Python code check


  formatting-check:
    jobs:
      - python-formatting-check:
          name: Python formatting check
  
  appimage:
    jobs:
      - appimage-upload:
          name: Create and upload appimage 
#          filters:
#            tags:
#              only: /[0-9]+(\.[0-9]+)*/
#            branches:
#              ignore: /.*/
